    steps:
    - uses: actions/checkout@v4 # Updated from v3

    - name: Set up Node.js
      uses: actions/setup-node@v4 # Updated from v3
      with:
        node-version: 18
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build
      env:
        CI: false

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4 # Updated from v3
      with:
        name: voucher-vault-web-build
        path: dist/
        
